# Generated by Django 5.1.6 on 2025-02-14 16:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                ("seat_price", models.PositiveBigIntegerField()),
                ("version", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Dining Table",
                "verbose_name_plural": "Dining Tables",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("cost_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cost_currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("CFM", "Confirmed"),
                            ("CNL", "Cancelled"),
                        ],
                        default="PND",
                        max_length=3,
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="booking.table",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cost_amount__gt", 0)),
                        name="positive_price",
                    ),
                ],
            },
        ),
    ]
